name: Deploy Frontend to Azure Container Apps

on:
  push:
    branches:
      - main
    paths:
      - "react-hooks-frontend/**"     #path to frontend
  workflow_dispatch:

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to ACR
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and Push Docker Image (Frontend)
        run: |
          cd react-hooks-frontend
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/my-frontend:latest .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/my-frontend:latest

      - name: Deploy Frontend to Azure Container Apps
        run: |
          az containerapp update \
            --name ${{ secrets.CONTAINER_APP_NAME_FRONTEND }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/my-frontend:latest
