name: Build and Push springboot Image

on:
  push:
    branches:
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build the application
        run: mvn clean package --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./springboot-backend  # Set the context to the directory containing the Dockerfile
          file: ./springboot-backend/Dockerfile  # Specify the Dockerfile location
          push: true  # Push the image to Docker Hub after building
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-spring-bootapp:latest

