name: Deploy backend to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and Push Docker Image (Backend)
        run: |
          cd springboot-backend
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/my-backend:latest .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/my-backend:latest

      - name: Deploy Backend to Azure Container Apps
        run: |
          az containerapp up \
            --name "${{ secrets.CONTAINER_APP_NAME_AUTO_BACKEND }}" \
            --resource-group "${{ secrets.RESOURCE_GROUP }}" \
            --environment "${{ secrets.CONTAINERAPPS_ENVIRONMENT }}" \
            --image "${{ secrets.ACR_NAME }}.azurecr.io/my-backend:latest" \
            --ingress external \
            --target-port 8080 \
            --env-vars \
              SPRING_DATASOURCE_URL="jdbc:mysql://${{ secrets.DB_HOST }}/${{ secrets.DB_NAME }}" \
              SPRING_DATASOURCE_USERNAME="${{ secrets.DB_USERNAME }}" \
              SPRING_DATASOURCE_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT="org.hibernate.dialect.MySQLDialect" \
              SPRING_JPA_HIBERNATE_DDL_AUTO="update"
